services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ~/homeassistant:/config
    network_mode: host
    privileged: true          # required for device access (Bluetooth, USB, etc.)

